export const fields = {
  brain2: [
    {
      value: "gender",
      label: "Gender",
      defaultValue: "1",
      type: "number",
    },
    {
      value: "age",
      label: "Age",
      defaultValue: 25,
      type: "number",
    },
    {
      value: "hypertension",
      label: "Hypertension",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "heart_disease",
      label: "Heart Disease",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "ever_married",
      label: "Ever Married",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "work_type",
      label: "Work Type",
      defaultValue: 2,
      type: "number",
    },
    {
      value: "Residence_type",
      label: "Residence Type",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "avg_glucose_level",
      label: "Average Glucose Level",
      defaultValue: 25,
      type: "number",
    },
    {
      value: "bmi",
      label: "BMI",
      defaultValue: 25,
      type: "number",
    },
    {
      value: "smoking_status",
      label: "Smoking Status",
      defaultValue: 0,
      type: "number",
    },
  ],
  heart2: [
    {
      value: "age",
      label: "Age",
      defaultValue: 45,
      type: "number",
    },
    {
      value: "anaemia",
      label: "Anaemia",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "creatinine_phosphokinase",
      label: "Creatinine Phosphokinase",
      defaultValue: 1876,
      type: "number",
    },
    {
      value: "diabetes",
      label: "Diabetes",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "ejection_fraction",
      label: "Ejection Fraction",
      defaultValue: 35,
      type: "number",
    },
    {
      value: "high_blood_pressure",
      label: "High Blood Pressure",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "platelets",
      label: "Platelets",
      defaultValue: 226000,
      type: "number",
    },
    {
      value: "serum_creatinine",
      label: "Serum Creatinine",
      defaultValue: 0.9,
      type: "number",
    },
    {
      value: "serum_sodium",
      label: "Serum Sodium",
      defaultValue: 138,
      type: "number",
    },
    {
      value: "sex",
      label: "Sex",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "smoking",
      label: "Smoking",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "time",
      label: "Time",
      defaultValue: 88,
      type: "number",
    },
  ],
  heart1: [
    {
      value: "Sex_Female",
      label: "Sex Female",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Sex_Male",
      label: "Sex Male",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "DM_0",
      label: "Diabetes 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "DM_1",
      label: "Diabetes 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "HTN_0",
      label: "Hypertension 0",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "HTN_1",
      label: "Hypertension 1",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Current_Smoker_0",
      label: "Current Smoker 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Current_Smoker_1",
      label: "Current Smoker 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "EX-Smoker_0",
      label: "Ex-Smoker 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "EX-Smoker_1",
      label: "Ex-Smoker 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "FH_0",
      label: "Family History 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "FH_1",
      label: "Family History 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Obesity_0",
      label: "Obesity 0",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Obesity_1",
      label: "Obesity 1",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "CRF_0",
      label: "CRF 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "CRF_1",
      label: "CRF 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "CVA_0",
      label: "CVA 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "CVA_1",
      label: "CVA 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Airway_disease_0",
      label: "Airway Disease 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Airway_disease_1",
      label: "Airway Disease 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Thyroid_Disease_0",
      label: "Thyroid Disease 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Thyroid_Disease_1",
      label: "Thyroid Disease 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "CHF_0",
      label: "CHF 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "CHF_1",
      label: "CHF 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "DLP_0",
      label: "DLP 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "DLP_1",
      label: "DLP 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Edema_0",
      label: "Edema 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Edema_1",
      label: "Edema 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Weak_Peripheral_Pulse_0",
      label: "Weak Peripheral Pulse 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Weak_Peripheral_Pulse_1",
      label: "Weak Peripheral Pulse 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Lung_rales_0",
      label: "Lung Rales 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Lung_rales_1",
      label: "Lung Rales 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Systolic_Murmur_0",
      label: "Systolic Murmur 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Systolic_Murmur_1",
      label: "Systolic Murmur 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Diastolic_Murmur_0",
      label: "Diastolic Murmur 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Diastolic_Murmur_1",
      label: "Diastolic Murmur 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Typical_Chest_Pain_0",
      label: "Typical Chest Pain 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Typical_Chest_Pain_1",
      label: "Typical Chest Pain 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Dyspnea_0",
      label: "Dyspnea 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Dyspnea_1",
      label: "Dyspnea 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Atypical_0",
      label: "Atypical 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Atypical_1",
      label: "Atypical 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Nonanginal_0",
      label: "Nonanginal 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Nonanginal_1",
      label: "Nonanginal 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Exertional_CP_0",
      label: "Exertional CP 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "LowTH_Ang_0",
      label: "LowTH Ang 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "LowTH_Ang_1",
      label: "LowTH Ang 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Q_Wave_0",
      label: "Q Wave 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Q_Wave_1",
      label: "Q Wave 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "St_Elevation_0",
      label: "St Elevation 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "St_Elevation_1",
      label: "St Elevation 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "St_Depression_0",
      label: "St Depression 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "St_Depression_1",
      label: "St Depression 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Tinversion_0",
      label: "Tinversion 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Tinversion_1",
      label: "Tinversion 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "LVH_0",
      label: "LVH 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "LVH_1",
      label: "LVH 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Poor_R_Progression_0",
      label: "Poor R Progression 0",
      defaultValue: 1,
      type: "number",
    },
    {
      value: "Poor_R_Progression_1",
      label: "Poor R Progression 1",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "Age",
      label: "Age",
      defaultValue: -0.8575992,
      type: "number",
    },
    {
      value: "Weight",
      label: "Weight",
      defaultValue: 1.1003343,
      type: "number",
    },
    {
      value: "Length",
      label: "Length",
      defaultValue: -1.25814528,
      type: "number",
    },
    {
      value: "BMI",
      label: "BMI",
      defaultValue: 2.42341694,
      type: "number",
    },
    {
      value: "BP",
      label: "BP",
      defaultValue: -1.03425361,
      type: "number",
    },
    {
      value: "PR",
      label: "PR",
      defaultValue: 0.54603133,
      type: "number",
    },
    {
      value: "FBS",
      label: "FBS",
      defaultValue: -0.29205145,
      type: "number",
    },
    {
      value: "CR",
      label: "CR",
      defaultValue: -0.210758,
      type: "number",
    },
    {
      value: "TG",
      label: "TG",
      defaultValue: 0.20099422,
      type: "number",
    },
    {
      value: "LDL",
      label: "LDL",
      defaultValue: 0.15157623,
      type: "number",
    },
    {
      value: "HDL",
      label: "HDL",
      defaultValue: 0.92642209,
      type: "number",
    },
    {
      value: "BUN",
      label: "BUN",
      defaultValue: -0.21621187,
      type: "number",
    },
    {
      value: "ESR",
      label: "ESR",
      defaultValue: 0.47378253,
      type: "number",
    },
    {
      value: "HB",
      label: "HB",
      defaultValue: 0.0289432,
      type: "number",
    },
    {
      value: "K",
      label: "K",
      defaultValue: -0.50430774,
      type: "number",
    },
    {
      value: "Na",
      label: "Na",
      defaultValue: -0.26217925,
      type: "number",
    },
    {
      value: "WBC",
      label: "WBC",
      defaultValue: 0.67971855,
      type: "number",
    },
    {
      value: "Lymph",
      label: "Lymph",
      defaultValue: 2.27002653,
      type: "number",
    },
    {
      value: "Neut",
      label: "Neut",
      defaultValue: -2.0803844,
      type: "number",
    },
    {
      value: "PLT",
      label: "PLT",
      defaultValue: 0.86515966,
      type: "number",
    },
    {
      value: "EF-TTE",
      label: "EF-TTE",
      defaultValue: 0.31068636,
      type: "number",
    },
    {
      value: "Function_Class",
      label: "Function Class",
      defaultValue: 2,
      type: "number",
    },
    {
      value: "Region_RWMA",
      label: "Region RWMA",
      defaultValue: 0,
      type: "number",
    },
    {
      value: "VHD",
      label: "VHD",
      defaultValue: 3,
      type: "number",
    },
  ],
};
