import { Inter } from "next/font/google";
import "../css/bootstrap.min.css";
import "../css/owl.carousel.min.css";
import "../css/magnific-popup.css";
import "../css/font-awesome.min.css";
import "../css/themify-icons.css";
import "../css/nice-select.css";
import "../css/flaticon.css";
import "../css/gijgo.css";
import "../css/animate.css";
import "../css/slicknav.css";
import "../css/style.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="no-js" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
